name: thrift2landlord
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6  
  provider: ^6.1.0 
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  google_maps_flutter: ^2.10.0
  # firebase_messaging: ^14.6.1
  # flutter_local_notifications: ^18.0.1
  intl: ^0.17.0  
  shared_preferences: ^2.2.0  
  image_picker: ^1.0.7  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  google_sign_in: ^6.2.2
  flutter_native_splash: ^2.4.4  # Correct placement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Ensure these paths are correct

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Karla-Bold.ttf  # Fixed filename (case-sensitive)
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/logo_light.jpeg
  image_dark: assets/images/logo_dark.jpeg
  android: true
  ios: true
  web: false
  fullscreen: true
