// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGaiEAXOi8lSD5TVRQl55hnUK7yMtwiXc',
    appId: '1:242712994832:web:df5b5599a23943ee5a5695',
    messagingSenderId: '242712994832',
    projectId: 'thrift2landlord-5be51',
    authDomain: 'thrift2landlord-5be51.firebaseapp.com',
    databaseURL: 'https://thrift2landlord-5be51-default-rtdb.firebaseio.com',
    storageBucket: 'thrift2landlord-5be51.firebasestorage.app',
    measurementId: 'G-0DDVY0DXQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkU5rxNB9n1uqhLMGy1lpzwkCan89-rY',
    appId: '1:242712994832:android:bedf97a05732e6265a5695',
    messagingSenderId: '242712994832',
    projectId: 'thrift2landlord-5be51',
    databaseURL: 'https://thrift2landlord-5be51-default-rtdb.firebaseio.com',
    storageBucket: 'thrift2landlord-5be51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFsZAPRUAQ8H_AywSOiUOU5LPj-MxOu_k',
    appId: '1:242712994832:ios:ce503967d8110b665a5695',
    messagingSenderId: '242712994832',
    projectId: 'thrift2landlord-5be51',
    databaseURL: 'https://thrift2landlord-5be51-default-rtdb.firebaseio.com',
    storageBucket: 'thrift2landlord-5be51.firebasestorage.app',
    iosBundleId: 'com.example.thrift2landlord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFsZAPRUAQ8H_AywSOiUOU5LPj-MxOu_k',
    appId: '1:242712994832:ios:ce503967d8110b665a5695',
    messagingSenderId: '242712994832',
    projectId: 'thrift2landlord-5be51',
    databaseURL: 'https://thrift2landlord-5be51-default-rtdb.firebaseio.com',
    storageBucket: 'thrift2landlord-5be51.firebasestorage.app',
    iosBundleId: 'com.example.thrift2landlord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGaiEAXOi8lSD5TVRQl55hnUK7yMtwiXc',
    appId: '1:242712994832:web:455511805c08f6c85a5695',
    messagingSenderId: '242712994832',
    projectId: 'thrift2landlord-5be51',
    authDomain: 'thrift2landlord-5be51.firebaseapp.com',
    databaseURL: 'https://thrift2landlord-5be51-default-rtdb.firebaseio.com',
    storageBucket: 'thrift2landlord-5be51.firebasestorage.app',
    measurementId: 'G-VX06ERELKR',
  );
}
